# Generated by Django 4.2.7 on 2024-01-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Msg',
        ),
    ]
